---
deployment:
    tasks:
        - /bin/rm -Rf $THEME_DIR
        - /bin/mkdir $THEME_DIR
        - /bin/cp -R $REPO_DIR/assets/ $THEME_DIR
        - /bin/cp -R $REPOPATH/lib/ $THEME_DIR
        - /bin/cp -R $REPOPATH/vendor/ $THEME_DIR
        - /bin/cp functions.php $THEME_DIR
        - /bin/cp style.css $THEME_DIR
