---
deployment:
    tasks:
        - export DEPLOYPATH=$HOME/public_html/lib/src/enogwe/
        - /bin/rm -Rf $DEPLOYPATH
        - /bin/mkdir $DEPLOYPATH
        - /usr/bin/rsync -a --delete --include="style.css" --include="functions.php" --include="assets" --include="lib" --include="vendor" $HOME/repositories/enogwe/ $DEPLOYPATH
