---
deployment:
    tasks:
        - export $REPOPATH=$HOME/repositories/enogwe/
        - export DEPLOYPATH=$HOME/public_html/lib/src/enogwe/
        - /bin/rm -Rf $DEPLOYPATH
        - /bin/mkdir $DEPLOYPATH
        - /bin/cp -R $REPOPATH/assets/ $DEPLOYPATH
        - /bin/cp -R $REPOPATH/lib/ $DEPLOYPATH
        - /bin/cp -R $REPOPATH/vendor/ $DEPLOYPATH
        - /bin/cp functions.php $DEPLOYPATH
        - /bin/cp style.css $DEPLOYPATH
