---
deployment:
    tasks:
        - export DEPLOYPATH=$HOME/public_html/lib/src/enogwe
        - /bin/cp -r assets/* $DEPLOYPATH
        - /bin/cp -r lib $DEPLOYPATH
        - /bin/cp -r vendor $DEPLOYPATH
        - /bin/cp functions.php $DEPLOYPATH
        - /bin/cp style.css $DEPLOYPATH
