version: 2.1
defaultsPhp: &defaultsPhp
    docker:
        - image: circleci/php:7.2-node-browsers
defaultsNode: &defaultsNode
    working_directory: ~/enogwe_node
    docker:
        - image: circleci/node:10
defaultsRelease: &defaultsRelease
    docker:
      - image: cibuilds/github:0.10
restoreCacheNode: &restoreCacheNode
    keys:
        - enogwe-node-cache-{{ checksum "package.json" }}
installPackagesNode:  &installPackagesNode
    name: install packages
    command: if (test ! -d ~/enogwe_node/node_modules); then npm ci; fi
jobs:
    build:
        <<: *defaultsNode
        steps:
            - checkout
            - restore_cache:
                <<: *restoreCacheNode
            - run:
                <<: *installPackagesNode
            - run:
                name: build theme
                command: npm run build
            - save_cache:
                key: enogwe-node-cache-{{ checksum "package.json" }}
                paths:
                    - ~/enogwe_node/node_modules
    test:
        <<: *defaultsPhp
        steps:
            - checkout
    release:
        <<: *defaultsNode
        steps:
            - checkout
            - restore_cache:
                <<: *restoreCacheNode
            - run:
                name: release
                command: npx semantic-release
workflows:
    version: 2
    build-test-release:
        jobs:
        - build
        - test:
            requires:
                - build
        - release:
            requires:
                - test
            filters:
                branches:
                    only:
                        - master


